# Generated by Django 4.1.3 on 2022-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='infoCity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoCountry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoIp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoOrganization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoPostal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoRegion',
            field=models.CharField(blank=True, max_length=58, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='infoTimezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
